variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build-debug-job:
  tags:
    - donut-abisko
    - windows

  stage: build
  script:
    - mkdir build_debug
    - cd build_debug
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . --target pt_sdk --config Debug
    - echo "Compile Debug complete."

build-release-job:
  tags:
    - donut-abisko
    - windows

  stage: build
  script:
    - mkdir build_release
    - cd build_release
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target pt_sdk --config Release
    - echo "Compile Release complete."